### ISSUE TITLE
Possible to skip the fetch calls on the server?

### ISSUE THREAD

**Issue by marbemac** [lxsmnsyc/thaler#9]
Similar to bling's approach (https://github.com/TanStack/bling).

"The function passed to server$ will only be executed on the server. On the client, a fetch call is made to the server function instead."

Basically in environments like cloudflare it's really nice to skip the http round trips during SSR for this data fetching. This also might introduce extra complexity at the infra level, depending on how the fetch calls are put together - e.g. dealing with a server making calls to itself back through the top level dns, since at least in our applications we explicitly disallow requests out to the public net for security reasons.

Thanks for the work on this library, I've enjoyed digging through the implementation and am pretty excited about where it could go!

**Comment by lxsmnsyc** [comment]
if the server function is called on the server, the function is called directly, there's no fetch call going to happen. That's what already happens in thaler.

**Comment by marbemac** [comment]
Ah yes I see now. I was thrown off because I started seeing this on the server, which made me think it was attempting to make an actual request (rather than simply creating a request object to pass into the callback context).

<img width="852" alt="Screenshot 2023-07-12 at 1 52 51 PM" src="https://github.com/lxsmnsyc/thaler/assets/847542/9ece2c64-d4e6-438d-a9b7-ae4d562d460c">

I opened a PR with a potential fix -> https://github.com/lxsmnsyc/thaler/pull/10.

**Comment by lxsmnsyc** [comment]
Should be fixed now in 0.7.1, thank you
